export const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);

export function legalMarkup(references = [], sources = new Map()) {
  if (!references.length) return '';
  return `<aside class="legal-basis"><h4>Fundamento e leitura na fonte</h4><ul>${references.map(reference => {
    const source = sources.get(reference.sourceId);
    const label = `${source?.title || reference.sourceId} — ${reference.locator}`;
    return `<li>${source ? `<a href="${escape(source.url)}" target="_blank" rel="noopener noreferrer">${escape(label)}</a>` : escape(label)}</li>`;
  }).join('')}</ul><small>Leia o dispositivo no contexto, incluindo condições, exceções e produção de efeitos.</small></aside>`;
}

export function answerFeedback(question, answer, sources = new Map()) {
  if (!Number.isInteger(answer) || !question.options[answer]) return '';
  return `<aside class="feedback" role="status"><b>${answer === question.correctIndex ? 'Resposta correta.' : `Gabarito: ${escape(question.options[question.correctIndex])}`}</b><p>${escape(question.optionExplanations?.[answer] || question.explanation)}</p>${question.optionExplanations ? `<details><summary>Por que as outras alternativas não se aplicam?</summary><ul>${question.options.map((option, index) => `<li><strong>${escape(option)}</strong> — ${escape(question.optionExplanations[index])}</li>`).join('')}</ul></details>` : ''}<p>${escape(question.explanation)}</p>${legalMarkup(question.legalRefs, sources)}</aside>`;
}

export function weekMarkup(week, sources = new Map(), media = null) {
  const sourceLinks = week.sourceIds.map(id => {
    const source = sources.get(id);
    return source ? `<a href="${escape(source.url)}" target="_blank" rel="noopener noreferrer">${escape(source.title)} <small>${escape(source.kind)}</small></a>` : `<span>Fonte: ${escape(id)}</span>`;
  }).join('');
  const list = items => `<ul>${items.map(item => `<li>${escape(item)}</li>`).join('')}</ul>`;
  const chapters = week.chapters.map(chapter => `<article class="chapter" id="${escape(chapter.id)}" data-audio-text="${escape(chapter.audioText)}"><h3>${escape(chapter.title)}</h3>${(chapter.paragraphs || [chapter.body]).map(p => `<p>${escape(p)}</p>`).join('')}${legalMarkup(chapter.legalRefs, sources)}<div class="audio-controls" data-audio-controls><button type="button" data-speak>Ouvir capítulo</button><button type="button" data-stop>Parar</button><label>Velocidade <select data-rate><option value="0.9">0,9x</option><option value="1" selected>1x</option><option value="1.25">1,25x</option></select></label></div></article>`).join('');
  const cases = (week.cases || []).map(item => `<article class="worked-case"><h4>${escape(item.title)}</h4>${list(item.facts)}<ol>${item.steps.map(step => `<li>${escape(step)}</li>`).join('')}</ol><p class="case-conclusion"><strong>Conclusão:</strong> ${escape(item.conclusion)}</p>${legalMarkup(item.legalRefs, sources)}</article>`).join('');
  const flow = week.flow.steps.map((step, index) => `<li><b>${String(index + 1).padStart(2, '0')} · ${escape(step.label)}</b><span>${escape(step.detail)}</span></li>`).join('');
  const todo = week.todo.map(item => `<label><input type="checkbox" data-week="${escape(week.id)}" data-todo="${escape(item.id)}"> ${escape(item.label)}</label>`).join('');
  const labList = (title, items) => `<section><h4>${title}</h4>${list(items)}</section>`;
  const mediaMarkup = media?.recordingUrl ? `<a href="${escape(media.recordingUrl)}" target="_blank" rel="noopener noreferrer">Assistir à gravação da aula</a>` : '<p class="media-pending">Não há gravação própria de 2h cadastrada nesta semana. Os vídeos abaixo são apoio, não comprovação da carga horária.</p>';
  const videos = (media?.supportVideos || []).map(video => `<div class="support-video"><iframe src="https://www.youtube-nocookie.com/embed/${escape(video.youtubeId)}" title="Vídeo: ${escape(video.title)}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="encrypted-media; picture-in-picture" allowfullscreen></iframe><p>${escape(video.title)}</p><a href="https://www.youtube.com/watch?v=${escape(video.youtubeId)}" target="_blank" rel="noopener noreferrer">Abrir no YouTube se o player não carregar</a></div>`).join('');
  return `<article class="program-week" id="${escape(week.id)}"><header><p>SEMANA ${String(week.number).padStart(2, '0')} · 6 HORAS DE ESTUDO PROGRAMADO</p><h2>${escape(week.title)}</h2><p class="week-outcomes">${escape(week.outcomes[0])}</p><small>Revisão editorial: ${escape(week.reviewedAt || '')}</small></header><nav class="chapter-index" aria-label="Capítulos da semana ${week.number}">${week.chapters.map(ch => `<a href="#${escape(ch.id)}">${escape(ch.title)}</a>`).join('')}</nav><p class="simulation-notice">${escape(week.simulationNotice || '')}</p><section class="weekly-chapters"><h3>Leitura guiada</h3>${chapters}</section>${cases ? `<section class="worked-cases"><h3>Casos resolvidos passo a passo</h3>${cases}</section>` : ''}<section class="decision-flow"><h3>${escape(week.flow.title)}</h3><ol class="flow-text">${flow}</ol></section><section class="week-todo"><h3>ToDoList semanal</h3>${todo}</section><section class="weekly-lab"><h3>Laboratório aplicado — resolva antes de conferir</h3>${labList('Fatos e premissas', week.lab.facts)}${labList('Documentos a reunir', week.lab.documents)}${labList('Decisões a justificar', week.lab.decisions)}${labList('Entregas esperadas', week.lab.evidence)}${week.lab.solution ? `<details class="lab-solution"><summary>Conferir resolução comentada</summary>${list(week.lab.solution)}</details>` : ''}</section><section class="study-agenda"><h3>Roteiro de 6 horas</h3><ol><li>120 min de estudo: 40 min de capítulos, 50 min de dispositivos na fonte e 30 min de anotações e dúvidas.</li><li>120 min de aula/debate; para estudo individual: 30 min revisando fontes, 45 min refazendo os casos sem gabarito e 45 min explicando as decisões por escrito. Vídeos de apoio podem compor esse bloco.</li><li>120 min de prática: 60 min de laboratório, 30 min de avaliação e correção, 30 min atualizando matriz e plano. Tempos são um roteiro, não medição automática.</li></ol></section><aside class="week-sources"><h3>Fontes e materiais complementares</h3>${sourceLinks}${mediaMarkup}</aside>${videos ? `<section class="support-videos"><h3>Vídeos de apoio — conferir data e escopo</h3>${videos}</section>` : ''}<section class="week-assessment"><h3>Avaliação da semana</h3><p>Meta: 80%. As alternativas têm justificativas; revise o fundamento de cada erro antes de refazer.</p><a href="questionario.html#${escape(week.id)}">Abrir avaliação</a>${week.number === 12 ? ' · <a href="questionario.html#final">Abrir exame integrador</a>' : ''}</section></article>`;
}
